from Bing_Image_Generator import Bing_Image_API

cookies=open('PATH TO YOUR COOKIES FILE','r')  # THIS LINE GETS THE COOKIES FROM THE COOKIES FILE SAVED IN THE DIRECTORY

prompt=input("Enter a prompt to generate an image: \n") #THIS LINE TAKES THE PROMPT FROM THE USER 

print(Bing_Image_API(cookies=cookies,prompt=prompt)) # SENDS THE REQUEST TO THE API AND PRINTS THE RESULT.


'''

TO GET THE COOKIES IN JSON FORMAT: 

STEP ONE: 
GO TO THIS LINK: 'https://chromewebstore.google.com/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm'
INSTALL THAT EXTENSION.

STEP TWO:
NOW OPEN THIS LINK: 'https://www.bing.com/images/create'

STEP THREE:
CLICK ON THE EXTENSION AND CLICK ON EXPORT ICON.
CLICK ON EXPORT AS JSON. IT WILL COPY THE COOKIES IN YOUR CLIPBOARD.

STEP FOUR:
OPEN YOUR VS-CODE AND OPEN CREATE A JSON FILE NAMED: 'COOKIES.JSON'
OPEN THE JSON FILE AND PASTE THE COOKIES YOU COPIED EARLIER.

STEP 5:
IMPORT THE COOKIES IN YOUR CODE AND ENJOY.

'''
